### ISSUE TITLE
Disabling Rain Rocket via config causes crash on startup

### ISSUE THREAD

**Issue by katubug** [Terpo/Waterworks#76] opened 2020-01-14 05:33 UTC
Hello! I attempted to disable/deregister the Rain Rocket, but I wanted to keep the Anti-Rain Rocket. As such, I changed only the config option for the Rain Rocket and it's recipe, changing both to false. I received the following crash: https://paste.dimdev.org/ubumolugih.mccrash

Here is a copy of my latest.log in case that is helpful: https://pastebin.com/YGi77LYw

I am using Waterworks version 1.1.0 in my main modpack instance with ~150 other mods. I did not test this in an isolated instance because I do not suspect it's a mod conflict, but I can do so if you'd like. I'm using Forge version 2847.

Thanks very much for your time! Please let me know if there's any other information I can provide :)

**Comment by Terpo** [comment] 2020-01-14 06:54
I will fix it in around 10h. Should be easy because the cause is, that I do not check if the rockets are actually available when adding the dispenser support.

**Comment by katubug** [comment] 2020-01-14 07:10
Sounds great! No rush, thank you very much for your response! :)

**Comment by Terpo** [comment] 2020-01-14 18:42
fixed in 1.1.1 Release on Curseforge

**Closed as completed by Terpo** 2020-01-14 18:42 UTC
Labels: bug, 1.12

**Comment by katubug** [comment] 2020-01-14 20:00
Thanks so much! :)
